name: deploy to staging
on: 
  push: 
    branches: 
     - main 

jobs: 
 
  deploy:
    name: deloying on staging ec2 cluster
    runs-on: ubuntu-latest
    steps:

    - name: performing action manually 
      run: |
        echo "${{secrets.PRIVATE_SSH_KEY}}" > ~/ssh_key
        chmod 400 ~/ssh_key
        ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.110.194.13 
        ls /
        cd /ChatApp
        pm2 kill
        npm install 
        pm2 start server.js --name chatapp

  

   